# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QFrame,
    QHeaderView, QLabel, QMainWindow, QSizePolicy,
    QStackedWidget, QStatusBar, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.actionsettings = QAction(MainWindow)
        self.actionsettings.setObjectName(u"actionsettings")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(20, 20, 771, 441))
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.accentStripe = QWidget(self.page_1)
        self.accentStripe.setObjectName(u"accentStripe")
        self.accentStripe.setGeometry(QRect(0, 0, 4, 22))
        self.accentStripe.setStyleSheet(u"background-color: rgb(232, 0, 45);")
        self.titleLabel = QLabel(self.page_1)
        self.titleLabel.setObjectName(u"titleLabel")
        self.titleLabel.setGeometry(QRect(12, 0, 300, 22))
        self.titleLabel.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 9px; background-color: transparent;")
        self.headerLine = QFrame(self.page_1)
        self.headerLine.setObjectName(u"headerLine")
        self.headerLine.setGeometry(QRect(0, 26, 771, 1))
        self.headerLine.setStyleSheet(u"background-color: rgb(26, 26, 26);")
        self.headerLine.setFrameShape(QFrame.Shape.HLine)
        self.frontBrakeTrack = QWidget(self.page_1)
        self.frontBrakeTrack.setObjectName(u"frontBrakeTrack")
        self.frontBrakeTrack.setGeometry(QRect(0, 68, 145, 310))
        self.frontBrakeTrack.setStyleSheet(u"background-color: rgb(10, 10, 10); border: 1px solid rgb(28, 28, 28);")
        self.frontbrakebar = QWidget(self.page_1)
        self.frontbrakebar.setObjectName(u"frontbrakebar")
        self.frontbrakebar.setEnabled(True)
        self.frontbrakebar.setGeometry(QRect(1, 223, 143, 155))
        self.frontbrakebar.setStyleSheet(u"background-color: rgb(86, 138, 219);")
        self.frontBrakeValueTop = QLabel(self.page_1)
        self.frontBrakeValueTop.setObjectName(u"frontBrakeValueTop")
        self.frontBrakeValueTop.setGeometry(QRect(52, 44, 50, 18))
        self.frontBrakeValueTop.setStyleSheet(u"color: rgb(86, 138, 219); font-family: \"Courier New\"; font-size: 10px; background-color: transparent;")
        self.frontBrakeValueTop.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label = QLabel(self.page_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(27, 392, 91, 22))
        self.label.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 8px; background-color: transparent;")
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.rearBrakeTrack = QWidget(self.page_1)
        self.rearBrakeTrack.setObjectName(u"rearBrakeTrack")
        self.rearBrakeTrack.setGeometry(QRect(145, 68, 145, 310))
        self.rearBrakeTrack.setStyleSheet(u"background-color: rgb(10, 10, 10); border: 1px solid rgb(28, 28, 28); border-left: none;")
        self.rearbrakebar = QWidget(self.page_1)
        self.rearbrakebar.setObjectName(u"rearbrakebar")
        self.rearbrakebar.setEnabled(True)
        self.rearbrakebar.setGeometry(QRect(146, 274, 143, 104))
        self.rearbrakebar.setStyleSheet(u"background-color: rgb(58, 101, 176);")
        self.rearBrakeValueTop = QLabel(self.page_1)
        self.rearBrakeValueTop.setObjectName(u"rearBrakeValueTop")
        self.rearBrakeValueTop.setGeometry(QRect(197, 44, 50, 18))
        self.rearBrakeValueTop.setStyleSheet(u"color: rgb(58, 101, 176); font-family: \"Courier New\"; font-size: 10px; background-color: transparent;")
        self.rearBrakeValueTop.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.page_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(172, 392, 91, 22))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 8px; background-color: transparent;")
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.speedTrack = QWidget(self.page_1)
        self.speedTrack.setObjectName(u"speedTrack")
        self.speedTrack.setGeometry(QRect(302, 68, 145, 310))
        self.speedTrack.setStyleSheet(u"background-color: rgb(10, 10, 10); border: 1px solid rgb(28, 28, 28);")
        self.speedbar = QWidget(self.page_1)
        self.speedbar.setObjectName(u"speedbar")
        self.speedbar.setEnabled(True)
        self.speedbar.setGeometry(QRect(303, 172, 143, 206))
        self.speedbar.setStyleSheet(u"background-color: rgb(232, 0, 45);")
        self.speedValueTop = QLabel(self.page_1)
        self.speedValueTop.setObjectName(u"speedValueTop")
        self.speedValueTop.setGeometry(QRect(355, 44, 40, 18))
        self.speedValueTop.setStyleSheet(u"color: rgb(232, 0, 45); font-family: \"Courier New\"; font-size: 10px; background-color: transparent;")
        self.speedValueTop.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_3 = QLabel(self.page_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(330, 392, 91, 22))
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 8px; background-color: transparent;")
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.throttleTrack = QWidget(self.page_1)
        self.throttleTrack.setObjectName(u"throttleTrack")
        self.throttleTrack.setGeometry(QRect(459, 68, 145, 310))
        self.throttleTrack.setStyleSheet(u"background-color: rgb(10, 10, 10); border: 1px solid rgb(28, 28, 28);")
        self.throttlebar = QWidget(self.page_1)
        self.throttlebar.setObjectName(u"throttlebar")
        self.throttlebar.setEnabled(True)
        self.throttlebar.setGeometry(QRect(460, 138, 143, 240))
        self.throttlebar.setStyleSheet(u"background-color: rgb(111, 154, 33);")
        self.throttleValueTop = QLabel(self.page_1)
        self.throttleValueTop.setObjectName(u"throttleValueTop")
        self.throttleValueTop.setGeometry(QRect(512, 44, 40, 18))
        self.throttleValueTop.setStyleSheet(u"color: rgb(111, 154, 33); font-family: \"Courier New\"; font-size: 10px; background-color: transparent;")
        self.throttleValueTop.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_4 = QLabel(self.page_1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(486, 392, 91, 22))
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 8px; background-color: transparent;")
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.statsPanel = QWidget(self.page_1)
        self.statsPanel.setObjectName(u"statsPanel")
        self.statsPanel.setGeometry(QRect(608, 242, 168, 136))
        self.statsPanel.setStyleSheet(u"background-color: rgb(13, 13, 13); border: 1px solid rgb(26, 26, 26); border-radius: 2px;")
        self.statFBLabel = QLabel(self.page_1)
        self.statFBLabel.setObjectName(u"statFBLabel")
        self.statFBLabel.setGeometry(QRect(620, 252, 130, 12))
        self.statFBLabel.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 9px; background-color: transparent;")
        self.statFBVal = QLabel(self.page_1)
        self.statFBVal.setObjectName(u"statFBVal")
        self.statFBVal.setGeometry(QRect(620, 267, 130, 14))
        self.statFBVal.setStyleSheet(u"color: rgb(86, 138, 219); font-family: \"Courier New\"; font-size: 11px; background-color: transparent;")
        self.statLine1 = QFrame(self.page_1)
        self.statLine1.setObjectName(u"statLine1")
        self.statLine1.setGeometry(QRect(620, 288, 130, 1))
        self.statLine1.setStyleSheet(u"background-color: rgb(26, 26, 26);")
        self.statLine1.setFrameShape(QFrame.Shape.HLine)
        self.statRBLabel = QLabel(self.page_1)
        self.statRBLabel.setObjectName(u"statRBLabel")
        self.statRBLabel.setGeometry(QRect(620, 294, 130, 12))
        self.statRBLabel.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 9px; background-color: transparent;")
        self.statRBVal = QLabel(self.page_1)
        self.statRBVal.setObjectName(u"statRBVal")
        self.statRBVal.setGeometry(QRect(620, 309, 130, 14))
        self.statRBVal.setStyleSheet(u"color: rgb(58, 101, 176); font-family: \"Courier New\"; font-size: 11px; background-color: transparent;")
        self.statLine2 = QFrame(self.page_1)
        self.statLine2.setObjectName(u"statLine2")
        self.statLine2.setGeometry(QRect(620, 330, 130, 1))
        self.statLine2.setStyleSheet(u"background-color: rgb(26, 26, 26);")
        self.statLine2.setFrameShape(QFrame.Shape.HLine)
        self.statSPLabel = QLabel(self.page_1)
        self.statSPLabel.setObjectName(u"statSPLabel")
        self.statSPLabel.setGeometry(QRect(620, 336, 68, 12))
        self.statSPLabel.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 9px; background-color: transparent;")
        self.statSPVal = QLabel(self.page_1)
        self.statSPVal.setObjectName(u"statSPVal")
        self.statSPVal.setGeometry(QRect(688, 336, 62, 12))
        self.statSPVal.setStyleSheet(u"color: rgb(232, 0, 45); font-family: \"Courier New\"; font-size: 10px; background-color: transparent;")
        self.statTHLabel = QLabel(self.page_1)
        self.statTHLabel.setObjectName(u"statTHLabel")
        self.statTHLabel.setGeometry(QRect(620, 352, 68, 12))
        self.statTHLabel.setStyleSheet(u"color: rgb(255, 255, 255); font-family: \"Courier New\"; font-size: 9px; background-color: transparent;")
        self.statTHVal = QLabel(self.page_1)
        self.statTHVal.setObjectName(u"statTHVal")
        self.statTHVal.setGeometry(QRect(688, 352, 62, 12))
        self.statTHVal.setStyleSheet(u"color: rgb(111, 154, 33); font-family: \"Courier New\"; font-size: 10px; background-color: transparent;")
        self.label_13 = QLabel(self.page_1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(610, 20, 151, 101))
        self.label_13.setStyleSheet(u"background-image: url(:/logo.png);")
        self.label_13.setPixmap(QPixmap(u"untitled/logo.png"))
        self.label_13.setScaledContents(True)
        self.stackedWidget.addWidget(self.page_1)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_7 = QLabel(self.page_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 30, 331, 91))
        font = QFont()
        font.setPointSize(40)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.pack_total_volt = QLabel(self.page_3)
        self.pack_total_volt.setObjectName(u"pack_total_volt")
        self.pack_total_volt.setGeometry(QRect(290, 110, 231, 91))
        self.pack_total_volt.setFont(font)
        self.pack_total_volt.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_9 = QLabel(self.page_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(290, 250, 171, 81))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.cell_volt = QLabel(self.page_3)
        self.cell_volt.setObjectName(u"cell_volt")
        self.cell_volt.setGeometry(QRect(280, 340, 181, 61))
        self.cell_volt.setFont(font)
        self.cell_volt.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.widget = QWidget(self.page_4)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(386, 10, 16, 421))
        self.widget.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.widget_2 = QWidget(self.page_4)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 211, 741, 16))
        self.widget_2.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.label_8 = QLabel(self.page_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 0, 171, 61))
        font1 = QFont()
        font1.setPointSize(25)
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_10 = QLabel(self.page_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(530, 10, 191, 41))
        self.label_10.setFont(font1)
        self.label_10.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_11 = QLabel(self.page_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 230, 171, 61))
        self.label_11.setFont(font1)
        self.label_11.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_12 = QLabel(self.page_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(410, 240, 361, 51))
        self.label_12.setFont(font1)
        self.label_12.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.running_perc = QLabel(self.page_4)
        self.running_perc.setObjectName(u"running_perc")
        self.running_perc.setGeometry(QRect(90, 100, 171, 51))
        font2 = QFont()
        font2.setPointSize(35)
        self.running_perc.setFont(font2)
        self.running_perc.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.gated_percent = QLabel(self.page_4)
        self.gated_percent.setObjectName(u"gated_percent")
        self.gated_percent.setGeometry(QRect(510, 90, 171, 51))
        self.gated_percent.setFont(font2)
        self.gated_percent.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.running_temp = QLabel(self.page_4)
        self.running_temp.setObjectName(u"running_temp")
        self.running_temp.setGeometry(QRect(90, 330, 171, 51))
        self.running_temp.setFont(font2)
        self.running_temp.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.cur_max_temp = QLabel(self.page_4)
        self.cur_max_temp.setObjectName(u"cur_max_temp")
        self.cur_max_temp.setGeometry(QRect(500, 330, 171, 51))
        self.cur_max_temp.setFont(font2)
        self.cur_max_temp.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.front_rear_temp_table = QTableWidget(self.page_5)
        if (self.front_rear_temp_table.columnCount() < 5):
            self.front_rear_temp_table.setColumnCount(5)
        if (self.front_rear_temp_table.rowCount() < 4):
            self.front_rear_temp_table.setRowCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 1, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 2, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 3, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 4, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 3, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 4, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 1, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 2, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 3, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 4, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 2, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 3, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 4, __qtablewidgetitem18)
        self.front_rear_temp_table.setObjectName(u"front_rear_temp_table")
        self.front_rear_temp_table.setGeometry(QRect(110, 10, 511, 221))
        font3 = QFont()
        font3.setPointSize(15)
        self.front_rear_temp_table.setFont(font3)
        self.front_rear_temp_table.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.front_rear_temp_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.front_rear_temp_table.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.front_rear_temp_table.setWordWrap(True)
        self.front_rear_temp_table.setRowCount(4)
        self.front_rear_temp_table.setColumnCount(5)
        self.front_rear_temp_table.horizontalHeader().setVisible(False)
        self.front_rear_temp_table.horizontalHeader().setCascadingSectionResizes(True)
        self.front_rear_temp_table.horizontalHeader().setDefaultSectionSize(100)
        self.front_rear_temp_table.horizontalHeader().setHighlightSections(True)
        self.front_rear_temp_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.front_rear_temp_table.horizontalHeader().setStretchLastSection(True)
        self.front_rear_temp_table.verticalHeader().setVisible(False)
        self.front_rear_temp_table.verticalHeader().setDefaultSectionSize(50)
        self.front_rear_temp_table.verticalHeader().setHighlightSections(True)
        self.front_rear_temp_table.verticalHeader().setProperty(u"showSortIndicator", False)
        self.front_rear_temp_table.verticalHeader().setStretchLastSection(True)
        self.motor_loop_temp_table = QTableWidget(self.page_5)
        if (self.motor_loop_temp_table.columnCount() < 3):
            self.motor_loop_temp_table.setColumnCount(3)
        if (self.motor_loop_temp_table.rowCount() < 2):
            self.motor_loop_temp_table.setRowCount(2)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(0, 0, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(0, 1, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(0, 2, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(1, 0, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(1, 1, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(1, 2, __qtablewidgetitem24)
        self.motor_loop_temp_table.setObjectName(u"motor_loop_temp_table")
        self.motor_loop_temp_table.setGeometry(QRect(0, 280, 321, 131))
        self.motor_loop_temp_table.setFont(font3)
        self.motor_loop_temp_table.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.motor_loop_temp_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.motor_loop_temp_table.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.motor_loop_temp_table.setWordWrap(True)
        self.motor_loop_temp_table.setRowCount(2)
        self.motor_loop_temp_table.setColumnCount(3)
        self.motor_loop_temp_table.horizontalHeader().setVisible(False)
        self.motor_loop_temp_table.horizontalHeader().setCascadingSectionResizes(True)
        self.motor_loop_temp_table.horizontalHeader().setDefaultSectionSize(100)
        self.motor_loop_temp_table.horizontalHeader().setHighlightSections(True)
        self.motor_loop_temp_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.motor_loop_temp_table.horizontalHeader().setStretchLastSection(True)
        self.motor_loop_temp_table.verticalHeader().setVisible(False)
        self.motor_loop_temp_table.verticalHeader().setDefaultSectionSize(50)
        self.motor_loop_temp_table.verticalHeader().setHighlightSections(True)
        self.motor_loop_temp_table.verticalHeader().setProperty(u"showSortIndicator", False)
        self.motor_loop_temp_table.verticalHeader().setStretchLastSection(True)
        self.inv_loop_temp_table = QTableWidget(self.page_5)
        if (self.inv_loop_temp_table.columnCount() < 3):
            self.inv_loop_temp_table.setColumnCount(3)
        if (self.inv_loop_temp_table.rowCount() < 2):
            self.inv_loop_temp_table.setRowCount(2)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(0, 0, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(0, 1, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(0, 2, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(1, 0, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(1, 1, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(1, 2, __qtablewidgetitem30)
        self.inv_loop_temp_table.setObjectName(u"inv_loop_temp_table")
        self.inv_loop_temp_table.setGeometry(QRect(400, 280, 321, 131))
        self.inv_loop_temp_table.setFont(font3)
        self.inv_loop_temp_table.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.inv_loop_temp_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.inv_loop_temp_table.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.inv_loop_temp_table.setWordWrap(True)
        self.inv_loop_temp_table.setRowCount(2)
        self.inv_loop_temp_table.setColumnCount(3)
        self.inv_loop_temp_table.horizontalHeader().setVisible(False)
        self.inv_loop_temp_table.horizontalHeader().setCascadingSectionResizes(True)
        self.inv_loop_temp_table.horizontalHeader().setDefaultSectionSize(100)
        self.inv_loop_temp_table.horizontalHeader().setHighlightSections(True)
        self.inv_loop_temp_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.inv_loop_temp_table.horizontalHeader().setStretchLastSection(True)
        self.inv_loop_temp_table.verticalHeader().setVisible(False)
        self.inv_loop_temp_table.verticalHeader().setDefaultSectionSize(50)
        self.inv_loop_temp_table.verticalHeader().setHighlightSections(True)
        self.inv_loop_temp_table.verticalHeader().setProperty(u"showSortIndicator", False)
        self.inv_loop_temp_table.verticalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.l1_light = QWidget(self.page_6)
        self.l1_light.setObjectName(u"l1_light")
        self.l1_light.setGeometry(QRect(300, 0, 41, 41))
        self.l1_light.setStyleSheet(u"background-color: rgb(255, 14, 30);\n"
"border-radius: 20px\n"
"")
        self.label_14 = QLabel(self.page_6)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 400, 91, 31))
        font4 = QFont()
        font4.setPointSize(7)
        self.label_14.setFont(font4)
        self.label_14.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.inverte_code_table = QTableWidget(self.page_6)
        if (self.inverte_code_table.columnCount() < 2):
            self.inverte_code_table.setColumnCount(2)
        if (self.inverte_code_table.rowCount() < 5):
            self.inverte_code_table.setRowCount(5)
        brush = QBrush(QColor(0, 0, 255, 255))
        brush.setStyle(Qt.BrushStyle.NoBrush)
        brush1 = QBrush(QColor(0, 0, 255, 255))
        brush1.setStyle(Qt.BrushStyle.NoBrush)
        font5 = QFont()
        font5.setPointSize(29)
        __qtablewidgetitem31 = QTableWidgetItem()
        __qtablewidgetitem31.setFont(font5);
        __qtablewidgetitem31.setBackground(brush1);
        __qtablewidgetitem31.setForeground(brush);
        self.inverte_code_table.setItem(0, 0, __qtablewidgetitem31)
        brush2 = QBrush(QColor(0, 0, 255, 255))
        brush2.setStyle(Qt.BrushStyle.NoBrush)
        __qtablewidgetitem32 = QTableWidgetItem()
        __qtablewidgetitem32.setFont(font5);
        __qtablewidgetitem32.setForeground(brush2);
        self.inverte_code_table.setItem(0, 1, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.inverte_code_table.setItem(1, 0, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.inverte_code_table.setItem(1, 1, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.inverte_code_table.setItem(2, 0, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.inverte_code_table.setItem(2, 1, __qtablewidgetitem36)
        font6 = QFont()
        font6.setPointSize(19)
        __qtablewidgetitem37 = QTableWidgetItem()
        __qtablewidgetitem37.setFont(font6);
        self.inverte_code_table.setItem(3, 0, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.inverte_code_table.setItem(3, 1, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.inverte_code_table.setItem(4, 0, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.inverte_code_table.setItem(4, 1, __qtablewidgetitem40)
        self.inverte_code_table.setObjectName(u"inverte_code_table")
        self.inverte_code_table.setEnabled(True)
        self.inverte_code_table.setGeometry(QRect(340, 110, 391, 281))
        self.inverte_code_table.setFont(font6)
        self.inverte_code_table.setStyleSheet(u"\n"
"color: rgb(255, 255, 255);\n"
"")
        self.inverte_code_table.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inverte_code_table.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.inverte_code_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.inverte_code_table.setRowCount(5)
        self.inverte_code_table.setColumnCount(2)
        self.inverte_code_table.horizontalHeader().setVisible(False)
        self.inverte_code_table.horizontalHeader().setCascadingSectionResizes(True)
        self.inverte_code_table.horizontalHeader().setDefaultSectionSize(250)
        self.inverte_code_table.horizontalHeader().setHighlightSections(True)
        self.inverte_code_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.inverte_code_table.horizontalHeader().setStretchLastSection(True)
        self.inverte_code_table.verticalHeader().setVisible(False)
        self.inverte_code_table.verticalHeader().setDefaultSectionSize(50)
        self.inverte_code_table.verticalHeader().setStretchLastSection(False)
        self.can1_util_bar_1 = QWidget(self.page_6)
        self.can1_util_bar_1.setObjectName(u"can1_util_bar_1")
        self.can1_util_bar_1.setEnabled(True)
        self.can1_util_bar_1.setGeometry(QRect(0, 30, 41, 371))
        self.can1_util_bar_1.setMaximumSize(QSize(100, 16777215))
        self.can1_util_bar_1.setStyleSheet(u"background-color:rgb(19, 255, 7)")
        self.l2_light = QWidget(self.page_6)
        self.l2_light.setObjectName(u"l2_light")
        self.l2_light.setGeometry(QRect(420, 0, 41, 41))
        self.l2_light.setStyleSheet(u"background-color: rgb(255, 14, 30);\n"
"border-radius: 20px\n"
"")
        self.l3_light = QWidget(self.page_6)
        self.l3_light.setObjectName(u"l3_light")
        self.l3_light.setGeometry(QRect(540, 0, 41, 41))
        self.l3_light.setStyleSheet(u"background-color: rgb(255, 14, 30);\n"
"border-radius: 20px\n"
"")
        self.l4_light = QWidget(self.page_6)
        self.l4_light.setObjectName(u"l4_light")
        self.l4_light.setGeometry(QRect(660, 0, 41, 41))
        self.l4_light.setStyleSheet(u"background-color: rgb(255, 14, 30);\n"
"border-radius: 20px\n"
"")
        self.label_15 = QLabel(self.page_6)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(530, 50, 91, 31))
        self.label_15.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_16 = QLabel(self.page_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(650, 50, 91, 31))
        self.label_16.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_17 = QLabel(self.page_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(410, 50, 91, 31))
        self.label_17.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.can1_util_bar_2 = QWidget(self.page_6)
        self.can1_util_bar_2.setObjectName(u"can1_util_bar_2")
        self.can1_util_bar_2.setEnabled(True)
        self.can1_util_bar_2.setGeometry(QRect(70, 30, 41, 371))
        self.can1_util_bar_2.setMaximumSize(QSize(100, 16777215))
        self.can1_util_bar_2.setStyleSheet(u"background-color:rgb(19, 255, 7)")
        self.can1_util_bar_3 = QWidget(self.page_6)
        self.can1_util_bar_3.setObjectName(u"can1_util_bar_3")
        self.can1_util_bar_3.setEnabled(True)
        self.can1_util_bar_3.setGeometry(QRect(140, 30, 41, 371))
        self.can1_util_bar_3.setMaximumSize(QSize(100, 16777215))
        self.can1_util_bar_3.setStyleSheet(u"background-color:rgb(19, 255, 7)")
        self.can1_util_bar_4 = QWidget(self.page_6)
        self.can1_util_bar_4.setObjectName(u"can1_util_bar_4")
        self.can1_util_bar_4.setEnabled(True)
        self.can1_util_bar_4.setGeometry(QRect(210, 30, 41, 371))
        self.can1_util_bar_4.setMaximumSize(QSize(100, 16777215))
        self.can1_util_bar_4.setStyleSheet(u"background-color:rgb(19, 255, 7)")
        self.label_18 = QLabel(self.page_6)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(70, 400, 91, 31))
        self.label_18.setFont(font4)
        self.label_18.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_19 = QLabel(self.page_6)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(140, 400, 91, 31))
        self.label_19.setFont(font4)
        self.label_19.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_19_2 = QLabel(self.page_6)
        self.label_19_2.setObjectName(u"label_19_2")
        self.label_19_2.setGeometry(QRect(210, 400, 91, 31))
        self.label_19_2.setFont(font4)
        self.label_19_2.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_21 = QLabel(self.page_6)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(300, 50, 91, 31))
        self.label_21.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.stackedWidget.addWidget(self.page_6)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.page_2.setStyleSheet(u"\n"
"QWidget#page_2 {\n"
"    background-color: #0a0a0a;\n"
"}\n"
"QLabel#bms_title {\n"
"    color: #f0f0f0;\n"
"    font-family: \"Courier New\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"}\n"
"QLabel#bms_subtitle {\n"
"    color: #555555;\n"
"    font-family: \"Courier New\";\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"}\n"
"QLabel#dotCharging, QLabel#dotBalancing {\n"
"    color: #E24B4A;\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"}\n"
"QLabel#statusChargingLabel, QLabel#statusBalancingLabel {\n"
"    color: #aaaaaa;\n"
"    font-family: \"Courier New\";\n"
"    font-size: 16px;\n"
"    background-color: transparent;\n"
"}\n"
"QLabel#badgeCharging, QLabel#badgeBalancing {\n"
"    background-color: rgba(226, 75, 74, 40);\n"
"    color: #E24B4A;\n"
"    font-family: \"Courier New\";\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgba(226, 75, 74, 80)"
                        ";\n"
"}\n"
"QFrame#bms_divider {\n"
"    background-color: rgba(255, 255, 255, 25);\n"
"}\n"
"QFrame#bmsCard1, QFrame#bmsCard2,\n"
"QFrame#bmsCard3, QFrame#bmsCard4,\n"
"QFrame#bmsCard5, QFrame#bmsCard6 {\n"
"    background-color: #161616;\n"
"    border: 1px solid rgba(255, 255, 255, 30);\n"
"    border-radius: 8px;\n"
"}\n"
"QLabel#lblCurrent, QLabel#lblVoltage,\n"
"QLabel#lblMinTemp, QLabel#lblMaxTemp,\n"
"QLabel#lblMinVolt, QLabel#lblMaxVolt {\n"
"    color: #555555;\n"
"    font-family: \"Courier New\";\n"
"    font-size: 12px;\n"
"    background-color: transparent;\n"
"}\n"
"QLabel#valCurrent, QLabel#valVoltage,\n"
"QLabel#valMinTemp, QLabel#valMaxTemp,\n"
"QLabel#valMinVolt, QLabel#valMaxVolt {\n"
"    color: #f0f0f0;\n"
"    font-family: \"Courier New\";\n"
"    font-size: 26px;\n"
"    font-weight: bold;\n"
"    background-color: transparent;\n"
"}\n"
"      ")
        self.bms_title = QLabel(self.page_2)
        self.bms_title.setObjectName(u"bms_title")
        self.bms_title.setGeometry(QRect(190, 16, 280, 28))
        self.bms_subtitle = QLabel(self.page_2)
        self.bms_subtitle.setObjectName(u"bms_subtitle")
        self.bms_subtitle.setGeometry(QRect(478, 16, 140, 28))
        self.bms_title_line = QFrame(self.page_2)
        self.bms_title_line.setObjectName(u"bms_title_line")
        self.bms_title_line.setGeometry(QRect(190, 48, 390, 1))
        self.bms_title_line.setStyleSheet(u"background-color: rgb(26, 26, 26);")
        self.bms_title_line.setFrameShape(QFrame.Shape.HLine)
        self.dotCharging = QLabel(self.page_2)
        self.dotCharging.setObjectName(u"dotCharging")
        self.dotCharging.setGeometry(QRect(190, 62, 18, 22))
        self.statusChargingLabel = QLabel(self.page_2)
        self.statusChargingLabel.setObjectName(u"statusChargingLabel")
        self.statusChargingLabel.setGeometry(QRect(216, 62, 150, 22))
        self.badgeCharging = QLabel(self.page_2)
        self.badgeCharging.setObjectName(u"badgeCharging")
        self.badgeCharging.setGeometry(QRect(382, 62, 54, 22))
        self.badgeCharging.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.dotBalancing = QLabel(self.page_2)
        self.dotBalancing.setObjectName(u"dotBalancing")
        self.dotBalancing.setGeometry(QRect(190, 92, 18, 22))
        self.statusBalancingLabel = QLabel(self.page_2)
        self.statusBalancingLabel.setObjectName(u"statusBalancingLabel")
        self.statusBalancingLabel.setGeometry(QRect(216, 92, 150, 22))
        self.badgeBalancing = QLabel(self.page_2)
        self.badgeBalancing.setObjectName(u"badgeBalancing")
        self.badgeBalancing.setGeometry(QRect(382, 92, 54, 22))
        self.badgeBalancing.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bms_divider = QFrame(self.page_2)
        self.bms_divider.setObjectName(u"bms_divider")
        self.bms_divider.setGeometry(QRect(110, 124, 550, 1))
        self.bms_divider.setFrameShape(QFrame.Shape.HLine)
        self.bms_divider.setFrameShadow(QFrame.Shadow.Plain)
        self.bmsCard1 = QFrame(self.page_2)
        self.bmsCard1.setObjectName(u"bmsCard1")
        self.bmsCard1.setGeometry(QRect(110, 160, 170, 110))
        self.lblCurrent = QLabel(self.bmsCard1)
        self.lblCurrent.setObjectName(u"lblCurrent")
        self.lblCurrent.setGeometry(QRect(12, 14, 146, 16))
        self.valCurrent = QLabel(self.bmsCard1)
        self.valCurrent.setObjectName(u"valCurrent")
        self.valCurrent.setGeometry(QRect(12, 42, 146, 38))
        self.bmsCard2 = QFrame(self.page_2)
        self.bmsCard2.setObjectName(u"bmsCard2")
        self.bmsCard2.setGeometry(QRect(300, 160, 170, 110))
        self.lblVoltage = QLabel(self.bmsCard2)
        self.lblVoltage.setObjectName(u"lblVoltage")
        self.lblVoltage.setGeometry(QRect(12, 14, 146, 16))
        self.valVoltage = QLabel(self.bmsCard2)
        self.valVoltage.setObjectName(u"valVoltage")
        self.valVoltage.setGeometry(QRect(12, 42, 146, 38))
        self.bmsCard3 = QFrame(self.page_2)
        self.bmsCard3.setObjectName(u"bmsCard3")
        self.bmsCard3.setGeometry(QRect(490, 160, 170, 110))
        self.lblMinTemp = QLabel(self.bmsCard3)
        self.lblMinTemp.setObjectName(u"lblMinTemp")
        self.lblMinTemp.setGeometry(QRect(12, 14, 146, 16))
        self.valMinTemp = QLabel(self.bmsCard3)
        self.valMinTemp.setObjectName(u"valMinTemp")
        self.valMinTemp.setGeometry(QRect(12, 42, 146, 38))
        self.bmsCard4 = QFrame(self.page_2)
        self.bmsCard4.setObjectName(u"bmsCard4")
        self.bmsCard4.setGeometry(QRect(110, 290, 170, 110))
        self.lblMaxTemp = QLabel(self.bmsCard4)
        self.lblMaxTemp.setObjectName(u"lblMaxTemp")
        self.lblMaxTemp.setGeometry(QRect(12, 14, 146, 16))
        self.valMaxTemp = QLabel(self.bmsCard4)
        self.valMaxTemp.setObjectName(u"valMaxTemp")
        self.valMaxTemp.setGeometry(QRect(12, 42, 146, 38))
        self.bmsCard5 = QFrame(self.page_2)
        self.bmsCard5.setObjectName(u"bmsCard5")
        self.bmsCard5.setGeometry(QRect(300, 290, 170, 110))
        self.lblMinVolt = QLabel(self.bmsCard5)
        self.lblMinVolt.setObjectName(u"lblMinVolt")
        self.lblMinVolt.setGeometry(QRect(12, 14, 146, 16))
        self.valMinVolt = QLabel(self.bmsCard5)
        self.valMinVolt.setObjectName(u"valMinVolt")
        self.valMinVolt.setGeometry(QRect(12, 42, 146, 38))
        self.bmsCard6 = QFrame(self.page_2)
        self.bmsCard6.setObjectName(u"bmsCard6")
        self.bmsCard6.setGeometry(QRect(490, 290, 170, 110))
        self.lblMaxVolt = QLabel(self.bmsCard6)
        self.lblMaxVolt.setObjectName(u"lblMaxVolt")
        self.lblMaxVolt.setGeometry(QRect(12, 14, 146, 16))
        self.valMaxVolt = QLabel(self.bmsCard6)
        self.valMaxVolt.setObjectName(u"valMaxVolt")
        self.valMaxVolt.setGeometry(QRect(12, 42, 146, 38))
        self.stackedWidget.addWidget(self.page_2)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.label_throttle_title = QLabel(self.page_7)
        self.label_throttle_title.setObjectName(u"label_throttle_title")
        self.label_throttle_title.setGeometry(QRect(0, 5, 771, 20))
        self.label_throttle_title.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.label_throttle_title.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.throttle_bar_bg = QWidget(self.page_7)
        self.throttle_bar_bg.setObjectName(u"throttle_bar_bg")
        self.throttle_bar_bg.setGeometry(QRect(10, 28, 581, 22))
        self.throttle_bar_bg.setStyleSheet(u"background-color: rgb(8, 255, 8)")
        self.throttle_bar_fill = QWidget(self.page_7)
        self.throttle_bar_fill.setObjectName(u"throttle_bar_fill")
        self.throttle_bar_fill.setGeometry(QRect(10, 28, 0, 22))
        self.throttle_bar_fill.setStyleSheet(u"background-color: rgb(0, 255, 0);")
        self.label_vx = QLabel(self.page_7)
        self.label_vx.setObjectName(u"label_vx")
        self.label_vx.setGeometry(QRect(8, 58, 257, 20))
        self.label_vx.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.vx_value = QLabel(self.page_7)
        self.vx_value.setObjectName(u"vx_value")
        self.vx_value.setGeometry(QRect(8, 78, 257, 50))
        font7 = QFont()
        font7.setPointSize(30)
        font7.setBold(True)
        self.vx_value.setFont(font7)
        self.vx_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_front_brake = QLabel(self.page_7)
        self.label_front_brake.setObjectName(u"label_front_brake")
        self.label_front_brake.setGeometry(QRect(265, 58, 257, 20))
        self.label_front_brake.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.front_brake_value = QLabel(self.page_7)
        self.front_brake_value.setObjectName(u"front_brake_value")
        self.front_brake_value.setGeometry(QRect(265, 78, 257, 50))
        self.front_brake_value.setFont(font7)
        self.front_brake_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_rear_brake = QLabel(self.page_7)
        self.label_rear_brake.setObjectName(u"label_rear_brake")
        self.label_rear_brake.setGeometry(QRect(522, 58, 249, 20))
        self.label_rear_brake.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.rear_brake_value = QLabel(self.page_7)
        self.rear_brake_value.setObjectName(u"rear_brake_value")
        self.rear_brake_value.setGeometry(QRect(522, 78, 249, 50))
        self.rear_brake_value.setFont(font7)
        self.rear_brake_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_imd_res = QLabel(self.page_7)
        self.label_imd_res.setObjectName(u"label_imd_res")
        self.label_imd_res.setGeometry(QRect(8, 138, 257, 20))
        self.label_imd_res.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.imd_res_value = QLabel(self.page_7)
        self.imd_res_value.setObjectName(u"imd_res_value")
        self.imd_res_value.setGeometry(QRect(8, 158, 257, 50))
        self.imd_res_value.setFont(font7)
        self.imd_res_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_total_volt = QLabel(self.page_7)
        self.label_total_volt.setObjectName(u"label_total_volt")
        self.label_total_volt.setGeometry(QRect(265, 138, 257, 20))
        self.label_total_volt.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.total_volt_value = QLabel(self.page_7)
        self.total_volt_value.setObjectName(u"total_volt_value")
        self.total_volt_value.setGeometry(QRect(265, 158, 257, 50))
        self.total_volt_value.setFont(font7)
        self.total_volt_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_fl_voltage = QLabel(self.page_7)
        self.label_fl_voltage.setObjectName(u"label_fl_voltage")
        self.label_fl_voltage.setGeometry(QRect(522, 138, 249, 20))
        self.label_fl_voltage.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.fl_voltage_value = QLabel(self.page_7)
        self.fl_voltage_value.setObjectName(u"fl_voltage_value")
        self.fl_voltage_value.setGeometry(QRect(522, 158, 249, 50))
        self.fl_voltage_value.setFont(font7)
        self.fl_voltage_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_fl_error = QLabel(self.page_7)
        self.label_fl_error.setObjectName(u"label_fl_error")
        self.label_fl_error.setGeometry(QRect(8, 218, 257, 20))
        self.label_fl_error.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.fl_error_value = QLabel(self.page_7)
        self.fl_error_value.setObjectName(u"fl_error_value")
        self.fl_error_value.setGeometry(QRect(8, 238, 257, 50))
        self.fl_error_value.setFont(font7)
        self.fl_error_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_rl_temp_inv = QLabel(self.page_7)
        self.label_rl_temp_inv.setObjectName(u"label_rl_temp_inv")
        self.label_rl_temp_inv.setGeometry(QRect(265, 218, 257, 20))
        self.label_rl_temp_inv.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.rl_temp_inv_value = QLabel(self.page_7)
        self.rl_temp_inv_value.setObjectName(u"rl_temp_inv_value")
        self.rl_temp_inv_value.setGeometry(QRect(265, 238, 257, 50))
        self.rl_temp_inv_value.setFont(font7)
        self.rl_temp_inv_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_rl_temp_motor = QLabel(self.page_7)
        self.label_rl_temp_motor.setObjectName(u"label_rl_temp_motor")
        self.label_rl_temp_motor.setGeometry(QRect(522, 218, 249, 20))
        self.label_rl_temp_motor.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.rl_temp_motor_value = QLabel(self.page_7)
        self.rl_temp_motor_value.setObjectName(u"rl_temp_motor_value")
        self.rl_temp_motor_value.setGeometry(QRect(522, 238, 249, 50))
        self.rl_temp_motor_value.setFont(font7)
        self.rl_temp_motor_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_rr_error = QLabel(self.page_7)
        self.label_rr_error.setObjectName(u"label_rr_error")
        self.label_rr_error.setGeometry(QRect(8, 298, 257, 20))
        self.label_rr_error.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.rr_error_value = QLabel(self.page_7)
        self.rr_error_value.setObjectName(u"rr_error_value")
        self.rr_error_value.setGeometry(QRect(8, 318, 257, 50))
        self.rr_error_value.setFont(font7)
        self.rr_error_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_rl_temp_igbt = QLabel(self.page_7)
        self.label_rl_temp_igbt.setObjectName(u"label_rl_temp_igbt")
        self.label_rl_temp_igbt.setGeometry(QRect(265, 298, 257, 20))
        self.label_rl_temp_igbt.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.rl_temp_igbt_value = QLabel(self.page_7)
        self.rl_temp_igbt_value.setObjectName(u"rl_temp_igbt_value")
        self.rl_temp_igbt_value.setGeometry(QRect(265, 318, 257, 50))
        self.rl_temp_igbt_value.setFont(font7)
        self.rl_temp_igbt_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.label_min_volt = QLabel(self.page_7)
        self.label_min_volt.setObjectName(u"label_min_volt")
        self.label_min_volt.setGeometry(QRect(522, 298, 249, 20))
        self.label_min_volt.setStyleSheet(u"color: rgb(255, 255, 255); font-weight: bold;")
        self.min_volt_value = QLabel(self.page_7)
        self.min_volt_value.setObjectName(u"min_volt_value")
        self.min_volt_value.setGeometry(QRect(522, 318, 249, 50))
        self.min_volt_value.setFont(font7)
        self.min_volt_value.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.fl_table = QTableWidget(self.page_8)
        if (self.fl_table.columnCount() < 2):
            self.fl_table.setColumnCount(2)
        if (self.fl_table.rowCount() < 4):
            self.fl_table.setRowCount(4)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.fl_table.setItem(0, 0, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.fl_table.setItem(0, 1, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.fl_table.setItem(1, 0, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.fl_table.setItem(1, 1, __qtablewidgetitem44)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.fl_table.setItem(2, 0, __qtablewidgetitem45)
        __qtablewidgetitem46 = QTableWidgetItem()
        self.fl_table.setItem(2, 1, __qtablewidgetitem46)
        __qtablewidgetitem47 = QTableWidgetItem()
        self.fl_table.setItem(3, 0, __qtablewidgetitem47)
        __qtablewidgetitem48 = QTableWidgetItem()
        self.fl_table.setItem(3, 1, __qtablewidgetitem48)
        self.fl_table.setObjectName(u"fl_table")
        self.fl_table.setGeometry(QRect(10, 10, 220, 121))
        font8 = QFont()
        font8.setPointSize(11)
        font8.setItalic(True)
        self.fl_table.setFont(font8)
        self.fl_table.setStyleSheet(u"color: rgb(255, 255, 255); border: 1px solid rgba(255,255,255,150);")
        self.fl_table.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fl_table.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fl_table.setRowCount(4)
        self.fl_table.setColumnCount(2)
        self.fl_table.horizontalHeader().setVisible(False)
        self.fl_table.horizontalHeader().setDefaultSectionSize(130)
        self.fl_table.horizontalHeader().setStretchLastSection(True)
        self.fl_table.verticalHeader().setVisible(False)
        self.fl_table.verticalHeader().setDefaultSectionSize(30)
        self.fr_table = QTableWidget(self.page_8)
        if (self.fr_table.columnCount() < 2):
            self.fr_table.setColumnCount(2)
        if (self.fr_table.rowCount() < 4):
            self.fr_table.setRowCount(4)
        __qtablewidgetitem49 = QTableWidgetItem()
        self.fr_table.setItem(0, 0, __qtablewidgetitem49)
        __qtablewidgetitem50 = QTableWidgetItem()
        self.fr_table.setItem(0, 1, __qtablewidgetitem50)
        __qtablewidgetitem51 = QTableWidgetItem()
        self.fr_table.setItem(1, 0, __qtablewidgetitem51)
        __qtablewidgetitem52 = QTableWidgetItem()
        self.fr_table.setItem(1, 1, __qtablewidgetitem52)
        __qtablewidgetitem53 = QTableWidgetItem()
        self.fr_table.setItem(2, 0, __qtablewidgetitem53)
        __qtablewidgetitem54 = QTableWidgetItem()
        self.fr_table.setItem(2, 1, __qtablewidgetitem54)
        __qtablewidgetitem55 = QTableWidgetItem()
        self.fr_table.setItem(3, 0, __qtablewidgetitem55)
        __qtablewidgetitem56 = QTableWidgetItem()
        self.fr_table.setItem(3, 1, __qtablewidgetitem56)
        self.fr_table.setObjectName(u"fr_table")
        self.fr_table.setGeometry(QRect(541, 10, 220, 131))
        self.fr_table.setFont(font8)
        self.fr_table.setStyleSheet(u"color: rgb(255, 255, 255); border: 1px solid rgba(255,255,255,150);")
        self.fr_table.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fr_table.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.fr_table.setRowCount(4)
        self.fr_table.setColumnCount(2)
        self.fr_table.horizontalHeader().setVisible(False)
        self.fr_table.horizontalHeader().setDefaultSectionSize(130)
        self.fr_table.horizontalHeader().setStretchLastSection(True)
        self.fr_table.verticalHeader().setVisible(False)
        self.fr_table.verticalHeader().setDefaultSectionSize(30)
        self.rl_table = QTableWidget(self.page_8)
        if (self.rl_table.columnCount() < 2):
            self.rl_table.setColumnCount(2)
        if (self.rl_table.rowCount() < 4):
            self.rl_table.setRowCount(4)
        __qtablewidgetitem57 = QTableWidgetItem()
        self.rl_table.setItem(0, 0, __qtablewidgetitem57)
        __qtablewidgetitem58 = QTableWidgetItem()
        self.rl_table.setItem(0, 1, __qtablewidgetitem58)
        __qtablewidgetitem59 = QTableWidgetItem()
        self.rl_table.setItem(1, 0, __qtablewidgetitem59)
        __qtablewidgetitem60 = QTableWidgetItem()
        self.rl_table.setItem(1, 1, __qtablewidgetitem60)
        __qtablewidgetitem61 = QTableWidgetItem()
        self.rl_table.setItem(2, 0, __qtablewidgetitem61)
        __qtablewidgetitem62 = QTableWidgetItem()
        self.rl_table.setItem(2, 1, __qtablewidgetitem62)
        __qtablewidgetitem63 = QTableWidgetItem()
        self.rl_table.setItem(3, 0, __qtablewidgetitem63)
        __qtablewidgetitem64 = QTableWidgetItem()
        self.rl_table.setItem(3, 1, __qtablewidgetitem64)
        self.rl_table.setObjectName(u"rl_table")
        self.rl_table.setGeometry(QRect(10, 310, 220, 121))
        self.rl_table.setFont(font8)
        self.rl_table.setStyleSheet(u"color: rgb(255, 255, 255); border: 1px solid rgba(255,255,255,150);")
        self.rl_table.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rl_table.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rl_table.setRowCount(4)
        self.rl_table.setColumnCount(2)
        self.rl_table.horizontalHeader().setVisible(False)
        self.rl_table.horizontalHeader().setDefaultSectionSize(130)
        self.rl_table.horizontalHeader().setStretchLastSection(True)
        self.rl_table.verticalHeader().setVisible(False)
        self.rl_table.verticalHeader().setDefaultSectionSize(30)
        self.rr_table = QTableWidget(self.page_8)
        if (self.rr_table.columnCount() < 2):
            self.rr_table.setColumnCount(2)
        if (self.rr_table.rowCount() < 4):
            self.rr_table.setRowCount(4)
        __qtablewidgetitem65 = QTableWidgetItem()
        self.rr_table.setItem(0, 0, __qtablewidgetitem65)
        __qtablewidgetitem66 = QTableWidgetItem()
        self.rr_table.setItem(0, 1, __qtablewidgetitem66)
        __qtablewidgetitem67 = QTableWidgetItem()
        self.rr_table.setItem(1, 0, __qtablewidgetitem67)
        __qtablewidgetitem68 = QTableWidgetItem()
        self.rr_table.setItem(1, 1, __qtablewidgetitem68)
        __qtablewidgetitem69 = QTableWidgetItem()
        self.rr_table.setItem(2, 0, __qtablewidgetitem69)
        __qtablewidgetitem70 = QTableWidgetItem()
        self.rr_table.setItem(2, 1, __qtablewidgetitem70)
        __qtablewidgetitem71 = QTableWidgetItem()
        self.rr_table.setItem(3, 0, __qtablewidgetitem71)
        __qtablewidgetitem72 = QTableWidgetItem()
        self.rr_table.setItem(3, 1, __qtablewidgetitem72)
        self.rr_table.setObjectName(u"rr_table")
        self.rr_table.setGeometry(QRect(540, 310, 220, 121))
        self.rr_table.setFont(font8)
        self.rr_table.setStyleSheet(u"color: rgb(255, 255, 255); border: 1px solid rgba(255,255,255,150);")
        self.rr_table.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rr_table.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.rr_table.setRowCount(4)
        self.rr_table.setColumnCount(2)
        self.rr_table.horizontalHeader().setVisible(False)
        self.rr_table.horizontalHeader().setDefaultSectionSize(130)
        self.rr_table.horizontalHeader().setStretchLastSection(True)
        self.rr_table.verticalHeader().setVisible(False)
        self.rr_table.verticalHeader().setDefaultSectionSize(30)
        self.car_svg_widget = QWidget(self.page_8)
        self.car_svg_widget.setObjectName(u"car_svg_widget")
        self.car_svg_widget.setGeometry(QRect(255, 5, 261, 431))
        self.car_svg_widget.setStyleSheet(u"background-color: transparent;")
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.page_9.setStyleSheet(u"\n"
"        QWidget#page_9 {\n"
"            background-color: rgb(15, 15, 15);\n"
"        }\n"
"        QLabel {\n"
"            color: rgb(255, 255, 255);\n"
"            font-family: Arial, sans-serif;\n"
"        }\n"
"      ")
        self.led_cell_volt = QWidget(self.page_9)
        self.led_cell_volt.setObjectName(u"led_cell_volt")
        self.led_cell_volt.setGeometry(QRect(10, 10, 24, 24))
        self.led_cell_volt.setStyleSheet(u"background-color: rgb(255, 0, 0); \n"
"border-radius: 12px; ")
        self.lbl_cell_volt_alarm = QLabel(self.page_9)
        self.lbl_cell_volt_alarm.setObjectName(u"lbl_cell_volt_alarm")
        self.lbl_cell_volt_alarm.setGeometry(QRect(45, 15, 200, 24))
        font9 = QFont()
        font9.setFamilies([u"Arial"])
        font9.setPointSize(14)
        self.lbl_cell_volt_alarm.setFont(font9)
        self.lbl_coolant_temp_alarm = QLabel(self.page_9)
        self.lbl_coolant_temp_alarm.setObjectName(u"lbl_coolant_temp_alarm")
        self.lbl_coolant_temp_alarm.setGeometry(QRect(45, 45, 311, 24))
        self.lbl_coolant_temp_alarm.setFont(font9)
        self.lbl_coolant_flow_alarm = QLabel(self.page_9)
        self.lbl_coolant_flow_alarm.setObjectName(u"lbl_coolant_flow_alarm")
        self.lbl_coolant_flow_alarm.setGeometry(QRect(45, 75, 200, 24))
        self.lbl_coolant_flow_alarm.setFont(font9)
        self.lbl_cell_temp_alarm = QLabel(self.page_9)
        self.lbl_cell_temp_alarm.setObjectName(u"lbl_cell_temp_alarm")
        self.lbl_cell_temp_alarm.setGeometry(QRect(520, 15, 200, 24))
        self.lbl_cell_temp_alarm.setFont(font9)
        self.lbl_cell_temp_alarm.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.led_cell_temp = QWidget(self.page_9)
        self.led_cell_temp.setObjectName(u"led_cell_temp")
        self.led_cell_temp.setGeometry(QRect(730, 15, 24, 24))
        self.led_cell_temp.setStyleSheet(u"background-color: rgb(255, 0, 0); \n"
"border-radius: 12px; ")
        self.lbl_hv_batt_ok = QLabel(self.page_9)
        self.lbl_hv_batt_ok.setObjectName(u"lbl_hv_batt_ok")
        self.lbl_hv_batt_ok.setGeometry(QRect(520, 45, 200, 24))
        self.lbl_hv_batt_ok.setFont(font9)
        self.lbl_hv_batt_ok.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.led_hv_batt_ok = QWidget(self.page_9)
        self.led_hv_batt_ok.setObjectName(u"led_hv_batt_ok")
        self.led_hv_batt_ok.setGeometry(QRect(730, 45, 24, 24))
        self.led_hv_batt_ok.setStyleSheet(u"background-color: rgb(255, 0, 0); \n"
"border-radius: 12px; ")
        self.lbl_can_ok = QLabel(self.page_9)
        self.lbl_can_ok.setObjectName(u"lbl_can_ok")
        self.lbl_can_ok.setGeometry(QRect(520, 75, 200, 24))
        self.lbl_can_ok.setFont(font9)
        self.lbl_can_ok.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.led_can_ok = QWidget(self.page_9)
        self.led_can_ok.setObjectName(u"led_can_ok")
        self.led_can_ok.setGeometry(QRect(730, 75, 24, 24))
        self.led_can_ok.setStyleSheet(u"background-color: rgb(255, 0, 0); \n"
"border-radius: 12px; ")
        self.val_speed = QLabel(self.page_9)
        self.val_speed.setObjectName(u"val_speed")
        self.val_speed.setGeometry(QRect(229, 80, 221, 150))
        font10 = QFont()
        font10.setFamilies([u"Arial"])
        font10.setPointSize(120)
        font10.setBold(True)
        self.val_speed.setFont(font10)
        self.val_speed.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_kmh = QLabel(self.page_9)
        self.lbl_kmh.setObjectName(u"lbl_kmh")
        self.lbl_kmh.setGeometry(QRect(460, 140, 201, 70))
        font11 = QFont()
        font11.setFamilies([u"Arial"])
        font11.setPointSize(45)
        font11.setBold(True)
        self.lbl_kmh.setFont(font11)
        self.val_soc = QLabel(self.page_9)
        self.val_soc.setObjectName(u"val_soc")
        self.val_soc.setGeometry(QRect(169, 240, 181, 50))
        font12 = QFont()
        font12.setFamilies([u"Arial"])
        font12.setPointSize(40)
        self.val_soc.setFont(font12)
        self.val_soc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_soc = QLabel(self.page_9)
        self.lbl_soc.setObjectName(u"lbl_soc")
        self.lbl_soc.setGeometry(QRect(190, 295, 160, 20))
        font13 = QFont()
        font13.setFamilies([u"Arial"])
        font13.setPointSize(14)
        font13.setItalic(True)
        self.lbl_soc.setFont(font13)
        self.lbl_soc.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.val_inv_volt = QLabel(self.page_9)
        self.val_inv_volt.setObjectName(u"val_inv_volt")
        self.val_inv_volt.setGeometry(QRect(390, 240, 181, 50))
        self.val_inv_volt.setFont(font12)
        self.val_inv_volt.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_inv_volt = QLabel(self.page_9)
        self.lbl_inv_volt.setObjectName(u"lbl_inv_volt")
        self.lbl_inv_volt.setGeometry(QRect(390, 295, 160, 20))
        self.lbl_inv_volt.setFont(font13)
        self.lbl_inv_volt.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_min_cell = QLabel(self.page_9)
        self.lbl_min_cell.setObjectName(u"lbl_min_cell")
        self.lbl_min_cell.setGeometry(QRect(10, 329, 180, 51))
        self.lbl_min_cell.setFont(font13)
        self.lbl_min_cell.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.val_min_cell = QLabel(self.page_9)
        self.val_min_cell.setObjectName(u"val_min_cell")
        self.val_min_cell.setGeometry(QRect(10, 385, 180, 45))
        font14 = QFont()
        font14.setFamilies([u"Arial"])
        font14.setPointSize(35)
        self.val_min_cell.setFont(font14)
        self.val_min_cell.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_max_igbt = QLabel(self.page_9)
        self.lbl_max_igbt.setObjectName(u"lbl_max_igbt")
        self.lbl_max_igbt.setGeometry(QRect(200, 329, 180, 51))
        self.lbl_max_igbt.setFont(font13)
        self.lbl_max_igbt.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.val_max_igbt = QLabel(self.page_9)
        self.val_max_igbt.setObjectName(u"val_max_igbt")
        self.val_max_igbt.setGeometry(QRect(200, 385, 180, 45))
        self.val_max_igbt.setFont(font14)
        self.val_max_igbt.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_max_inv = QLabel(self.page_9)
        self.lbl_max_inv.setObjectName(u"lbl_max_inv")
        self.lbl_max_inv.setGeometry(QRect(390, 329, 180, 51))
        self.lbl_max_inv.setFont(font13)
        self.lbl_max_inv.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.val_max_inv = QLabel(self.page_9)
        self.val_max_inv.setObjectName(u"val_max_inv")
        self.val_max_inv.setGeometry(QRect(390, 385, 180, 45))
        self.val_max_inv.setFont(font14)
        self.val_max_inv.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_max_motor = QLabel(self.page_9)
        self.lbl_max_motor.setObjectName(u"lbl_max_motor")
        self.lbl_max_motor.setGeometry(QRect(580, 329, 180, 51))
        self.lbl_max_motor.setFont(font13)
        self.lbl_max_motor.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.val_max_motor = QLabel(self.page_9)
        self.val_max_motor.setObjectName(u"val_max_motor")
        self.val_max_motor.setGeometry(QRect(580, 385, 180, 45))
        self.val_max_motor.setFont(font14)
        self.val_max_motor.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.led_cell_volt_2 = QWidget(self.page_9)
        self.led_cell_volt_2.setObjectName(u"led_cell_volt_2")
        self.led_cell_volt_2.setGeometry(QRect(10, 40, 24, 24))
        self.led_cell_volt_2.setStyleSheet(u"background-color: rgb(255, 0, 0); \n"
"border-radius: 12px; ")
        self.led_cell_volt_3 = QWidget(self.page_9)
        self.led_cell_volt_3.setObjectName(u"led_cell_volt_3")
        self.led_cell_volt_3.setGeometry(QRect(10, 70, 24, 24))
        self.led_cell_volt_3.setStyleSheet(u"background-color: rgb(255, 0, 0); \n"
"border-radius: 12px; ")
        self.stackedWidget.addWidget(self.page_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(5)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionsettings.setText(QCoreApplication.translate("MainWindow", u"settings", None))
        self.titleLabel.setText(QCoreApplication.translate("MainWindow", u"TELEMETRY - INPUT TRACE", None))
        self.frontBrakeValueTop.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"FRONT BRAKE", None))
        self.rearBrakeValueTop.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"REAR BRAKE", None))
        self.speedValueTop.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"SPEED", None))
        self.throttleValueTop.setText(QCoreApplication.translate("MainWindow", u"0%", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"THROTTLE", None))
        self.statFBLabel.setText(QCoreApplication.translate("MainWindow", u"FRONT BRAKE", None))
        self.statFBVal.setText(QCoreApplication.translate("MainWindow", u"-- %", None))
        self.statRBLabel.setText(QCoreApplication.translate("MainWindow", u"REAR BRAKE", None))
        self.statRBVal.setText(QCoreApplication.translate("MainWindow", u"-- %", None))
        self.statSPLabel.setText(QCoreApplication.translate("MainWindow", u"SPEED", None))
        self.statSPVal.setText(QCoreApplication.translate("MainWindow", u"-- km/h", None))
        self.statTHLabel.setText(QCoreApplication.translate("MainWindow", u"THROTTLE", None))
        self.statTHVal.setText(QCoreApplication.translate("MainWindow", u"-- %", None))
        self.label_13.setText("")
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Pack Total", None))
        self.pack_total_volt.setText(QCoreApplication.translate("MainWindow", u"000V", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Cell", None))
        self.cell_volt.setText(QCoreApplication.translate("MainWindow", u"000V", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Running", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Gated", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Running", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Current Max Temp.", None))
        self.running_perc.setText(QCoreApplication.translate("MainWindow", u"00.0%", None))
        self.gated_percent.setText(QCoreApplication.translate("MainWindow", u"00.0%", None))
        self.running_temp.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.cur_max_temp.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))

        __sortingEnabled = self.front_rear_temp_table.isSortingEnabled()
        self.front_rear_temp_table.setSortingEnabled(False)
        ___qtablewidgetitem = self.front_rear_temp_table.item(0, 1)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"FL", None));
        ___qtablewidgetitem1 = self.front_rear_temp_table.item(0, 2)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"FR", None));
        ___qtablewidgetitem2 = self.front_rear_temp_table.item(0, 3)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"RL", None));
        ___qtablewidgetitem3 = self.front_rear_temp_table.item(0, 4)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"RR", None));
        ___qtablewidgetitem4 = self.front_rear_temp_table.item(1, 0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Motor", None));
        ___qtablewidgetitem5 = self.front_rear_temp_table.item(1, 1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem6 = self.front_rear_temp_table.item(1, 2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem7 = self.front_rear_temp_table.item(1, 3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem8 = self.front_rear_temp_table.item(1, 4)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem9 = self.front_rear_temp_table.item(2, 0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"IGBT", None));
        ___qtablewidgetitem10 = self.front_rear_temp_table.item(2, 1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem11 = self.front_rear_temp_table.item(2, 2)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem12 = self.front_rear_temp_table.item(2, 3)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem13 = self.front_rear_temp_table.item(2, 4)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem14 = self.front_rear_temp_table.item(3, 0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Cold Plate", None));
        ___qtablewidgetitem15 = self.front_rear_temp_table.item(3, 1)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem16 = self.front_rear_temp_table.item(3, 2)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem17 = self.front_rear_temp_table.item(3, 3)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem18 = self.front_rear_temp_table.item(3, 4)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        self.front_rear_temp_table.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.motor_loop_temp_table.isSortingEnabled()
        self.motor_loop_temp_table.setSortingEnabled(False)
        ___qtablewidgetitem19 = self.motor_loop_temp_table.item(0, 1)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Start", None));
        ___qtablewidgetitem20 = self.motor_loop_temp_table.item(0, 2)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"End", None));
        ___qtablewidgetitem21 = self.motor_loop_temp_table.item(1, 0)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"Motor Loop", None));
        ___qtablewidgetitem22 = self.motor_loop_temp_table.item(1, 1)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem23 = self.motor_loop_temp_table.item(1, 2)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        self.motor_loop_temp_table.setSortingEnabled(__sortingEnabled1)


        __sortingEnabled2 = self.inv_loop_temp_table.isSortingEnabled()
        self.inv_loop_temp_table.setSortingEnabled(False)
        ___qtablewidgetitem24 = self.inv_loop_temp_table.item(0, 1)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"Start", None));
        ___qtablewidgetitem25 = self.inv_loop_temp_table.item(0, 2)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"End", None));
        ___qtablewidgetitem26 = self.inv_loop_temp_table.item(1, 0)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"Inverter Loop", None));
        ___qtablewidgetitem27 = self.inv_loop_temp_table.item(1, 1)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem28 = self.inv_loop_temp_table.item(1, 2)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        self.inv_loop_temp_table.setSortingEnabled(__sortingEnabled2)

        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Can 1", None))

        __sortingEnabled3 = self.inverte_code_table.isSortingEnabled()
        self.inverte_code_table.setSortingEnabled(False)
        ___qtablewidgetitem29 = self.inverte_code_table.item(0, 0)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"Inverter", None));
        ___qtablewidgetitem30 = self.inverte_code_table.item(0, 1)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"Code", None));
        ___qtablewidgetitem31 = self.inverte_code_table.item(1, 0)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"Inverter 1", None));
        ___qtablewidgetitem32 = self.inverte_code_table.item(1, 1)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"0", None));
        ___qtablewidgetitem33 = self.inverte_code_table.item(2, 0)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"Inverter 2", None));
        ___qtablewidgetitem34 = self.inverte_code_table.item(2, 1)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"0", None));
        ___qtablewidgetitem35 = self.inverte_code_table.item(3, 0)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"Inverter 3", None));
        ___qtablewidgetitem36 = self.inverte_code_table.item(3, 1)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"0", None));
        ___qtablewidgetitem37 = self.inverte_code_table.item(4, 0)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"Inverter 4", None));
        ___qtablewidgetitem38 = self.inverte_code_table.item(4, 1)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"0", None));
        self.inverte_code_table.setSortingEnabled(__sortingEnabled3)

        self.label_15.setText(QCoreApplication.translate("MainWindow", u"L3 error", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"L4 error", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"L2 error", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Can 1", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Can 1", None))
        self.label_19_2.setText(QCoreApplication.translate("MainWindow", u"Can 1", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"L1 error", None))
        self.bms_title.setText(QCoreApplication.translate("MainWindow", u"Battery Management", None))
        self.bms_subtitle.setText(QCoreApplication.translate("MainWindow", u"BMS Monitor", None))
        self.dotCharging.setText(QCoreApplication.translate("MainWindow", u"\u25cf", None))
        self.statusChargingLabel.setText(QCoreApplication.translate("MainWindow", u"Charging", None))
        self.badgeCharging.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.dotBalancing.setText(QCoreApplication.translate("MainWindow", u"\u25cf", None))
        self.statusBalancingLabel.setText(QCoreApplication.translate("MainWindow", u"Balancing", None))
        self.badgeBalancing.setText(QCoreApplication.translate("MainWindow", u"Off", None))
        self.lblCurrent.setText(QCoreApplication.translate("MainWindow", u"CURRENT", None))
        self.valCurrent.setText(QCoreApplication.translate("MainWindow", u"0 A", None))
        self.lblVoltage.setText(QCoreApplication.translate("MainWindow", u"VOLTAGE", None))
        self.valVoltage.setText(QCoreApplication.translate("MainWindow", u"0 V", None))
        self.lblMinTemp.setText(QCoreApplication.translate("MainWindow", u"MIN CELL TEMP", None))
        self.valMinTemp.setText(QCoreApplication.translate("MainWindow", u"0 \u00b0C", None))
        self.lblMaxTemp.setText(QCoreApplication.translate("MainWindow", u"MAX CELL TEMP", None))
        self.valMaxTemp.setText(QCoreApplication.translate("MainWindow", u"0 \u00b0C", None))
        self.lblMinVolt.setText(QCoreApplication.translate("MainWindow", u"MIN CELL VOLT", None))
        self.valMinVolt.setText(QCoreApplication.translate("MainWindow", u"0 V", None))
        self.lblMaxVolt.setText(QCoreApplication.translate("MainWindow", u"MAX CELL VOLT", None))
        self.valMaxVolt.setText(QCoreApplication.translate("MainWindow", u"0 V", None))
        self.label_throttle_title.setText(QCoreApplication.translate("MainWindow", u"Throttle Percentage", None))
        self.label_vx.setText(QCoreApplication.translate("MainWindow", u"Vx", None))
        self.vx_value.setText(QCoreApplication.translate("MainWindow", u"00 km/h", None))
        self.label_front_brake.setText(QCoreApplication.translate("MainWindow", u"Front Brake Pressure", None))
        self.front_brake_value.setText(QCoreApplication.translate("MainWindow", u"00.0 bar", None))
        self.label_rear_brake.setText(QCoreApplication.translate("MainWindow", u"Rear Brake Pressure", None))
        self.rear_brake_value.setText(QCoreApplication.translate("MainWindow", u"00.0 bar", None))
        self.label_imd_res.setText(QCoreApplication.translate("MainWindow", u"IMD RES", None))
        self.imd_res_value.setText(QCoreApplication.translate("MainWindow", u"000 kOhm", None))
        self.label_total_volt.setText(QCoreApplication.translate("MainWindow", u"TOTAL VOLT", None))
        self.total_volt_value.setText(QCoreApplication.translate("MainWindow", u"000 V", None))
        self.label_fl_voltage.setText(QCoreApplication.translate("MainWindow", u"FL Voltage", None))
        self.fl_voltage_value.setText(QCoreApplication.translate("MainWindow", u"000 V", None))
        self.label_fl_error.setText(QCoreApplication.translate("MainWindow", u"FL Error Info", None))
        self.fl_error_value.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.label_rl_temp_inv.setText(QCoreApplication.translate("MainWindow", u"RL Temp Inverter", None))
        self.rl_temp_inv_value.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.label_rl_temp_motor.setText(QCoreApplication.translate("MainWindow", u"RL Temp Motor", None))
        self.rl_temp_motor_value.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.label_rr_error.setText(QCoreApplication.translate("MainWindow", u"RR Error Info", None))
        self.rr_error_value.setText(QCoreApplication.translate("MainWindow", u"0000", None))
        self.label_rl_temp_igbt.setText(QCoreApplication.translate("MainWindow", u"RL Temp IGBT", None))
        self.rl_temp_igbt_value.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.label_min_volt.setText(QCoreApplication.translate("MainWindow", u"Min Volt", None))
        self.min_volt_value.setText(QCoreApplication.translate("MainWindow", u"0.00 V", None))

        __sortingEnabled4 = self.fl_table.isSortingEnabled()
        self.fl_table.setSortingEnabled(False)
        ___qtablewidgetitem39 = self.fl_table.item(0, 0)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"Wheel Speed", None));
        ___qtablewidgetitem40 = self.fl_table.item(0, 1)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"0000", None));
        ___qtablewidgetitem41 = self.fl_table.item(1, 0)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("MainWindow", u"Torque", None));
        ___qtablewidgetitem42 = self.fl_table.item(1, 1)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("MainWindow", u"0.0", None));
        ___qtablewidgetitem43 = self.fl_table.item(2, 0)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("MainWindow", u"Rot Pot", None));
        ___qtablewidgetitem44 = self.fl_table.item(2, 1)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        ___qtablewidgetitem45 = self.fl_table.item(3, 0)
        ___qtablewidgetitem45.setText(QCoreApplication.translate("MainWindow", u"Brake Temp", None));
        ___qtablewidgetitem46 = self.fl_table.item(3, 1)
        ___qtablewidgetitem46.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        self.fl_table.setSortingEnabled(__sortingEnabled4)


        __sortingEnabled5 = self.fr_table.isSortingEnabled()
        self.fr_table.setSortingEnabled(False)
        ___qtablewidgetitem47 = self.fr_table.item(0, 0)
        ___qtablewidgetitem47.setText(QCoreApplication.translate("MainWindow", u"Wheel Speed", None));
        ___qtablewidgetitem48 = self.fr_table.item(0, 1)
        ___qtablewidgetitem48.setText(QCoreApplication.translate("MainWindow", u"0000", None));
        ___qtablewidgetitem49 = self.fr_table.item(1, 0)
        ___qtablewidgetitem49.setText(QCoreApplication.translate("MainWindow", u"Torque", None));
        ___qtablewidgetitem50 = self.fr_table.item(1, 1)
        ___qtablewidgetitem50.setText(QCoreApplication.translate("MainWindow", u"0.0", None));
        ___qtablewidgetitem51 = self.fr_table.item(2, 0)
        ___qtablewidgetitem51.setText(QCoreApplication.translate("MainWindow", u"Rot Pot", None));
        ___qtablewidgetitem52 = self.fr_table.item(2, 1)
        ___qtablewidgetitem52.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        ___qtablewidgetitem53 = self.fr_table.item(3, 0)
        ___qtablewidgetitem53.setText(QCoreApplication.translate("MainWindow", u"Brake Temp", None));
        ___qtablewidgetitem54 = self.fr_table.item(3, 1)
        ___qtablewidgetitem54.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        self.fr_table.setSortingEnabled(__sortingEnabled5)


        __sortingEnabled6 = self.rl_table.isSortingEnabled()
        self.rl_table.setSortingEnabled(False)
        ___qtablewidgetitem55 = self.rl_table.item(0, 0)
        ___qtablewidgetitem55.setText(QCoreApplication.translate("MainWindow", u"Wheel Speed", None));
        ___qtablewidgetitem56 = self.rl_table.item(0, 1)
        ___qtablewidgetitem56.setText(QCoreApplication.translate("MainWindow", u"0000", None));
        ___qtablewidgetitem57 = self.rl_table.item(1, 0)
        ___qtablewidgetitem57.setText(QCoreApplication.translate("MainWindow", u"Torque", None));
        ___qtablewidgetitem58 = self.rl_table.item(1, 1)
        ___qtablewidgetitem58.setText(QCoreApplication.translate("MainWindow", u"0.0", None));
        ___qtablewidgetitem59 = self.rl_table.item(2, 0)
        ___qtablewidgetitem59.setText(QCoreApplication.translate("MainWindow", u"Rot Pot", None));
        ___qtablewidgetitem60 = self.rl_table.item(2, 1)
        ___qtablewidgetitem60.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        ___qtablewidgetitem61 = self.rl_table.item(3, 0)
        ___qtablewidgetitem61.setText(QCoreApplication.translate("MainWindow", u"Brake Temp", None));
        ___qtablewidgetitem62 = self.rl_table.item(3, 1)
        ___qtablewidgetitem62.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        self.rl_table.setSortingEnabled(__sortingEnabled6)


        __sortingEnabled7 = self.rr_table.isSortingEnabled()
        self.rr_table.setSortingEnabled(False)
        ___qtablewidgetitem63 = self.rr_table.item(0, 0)
        ___qtablewidgetitem63.setText(QCoreApplication.translate("MainWindow", u"Wheel Speed", None));
        ___qtablewidgetitem64 = self.rr_table.item(0, 1)
        ___qtablewidgetitem64.setText(QCoreApplication.translate("MainWindow", u"0000", None));
        ___qtablewidgetitem65 = self.rr_table.item(1, 0)
        ___qtablewidgetitem65.setText(QCoreApplication.translate("MainWindow", u"Torque", None));
        ___qtablewidgetitem66 = self.rr_table.item(1, 1)
        ___qtablewidgetitem66.setText(QCoreApplication.translate("MainWindow", u"0.0", None));
        ___qtablewidgetitem67 = self.rr_table.item(2, 0)
        ___qtablewidgetitem67.setText(QCoreApplication.translate("MainWindow", u"Rot Pot", None));
        ___qtablewidgetitem68 = self.rr_table.item(2, 1)
        ___qtablewidgetitem68.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        ___qtablewidgetitem69 = self.rr_table.item(3, 0)
        ___qtablewidgetitem69.setText(QCoreApplication.translate("MainWindow", u"Brake Temp", None));
        ___qtablewidgetitem70 = self.rr_table.item(3, 1)
        ___qtablewidgetitem70.setText(QCoreApplication.translate("MainWindow", u"00.0", None));
        self.rr_table.setSortingEnabled(__sortingEnabled7)

        self.lbl_cell_volt_alarm.setText(QCoreApplication.translate("MainWindow", u"Cell Voltage Alarm", None))
        self.lbl_coolant_temp_alarm.setText(QCoreApplication.translate("MainWindow", u"Coolant Temperature Alarm", None))
        self.lbl_coolant_flow_alarm.setText(QCoreApplication.translate("MainWindow", u"Coolant Flow Alarm", None))
        self.lbl_cell_temp_alarm.setText(QCoreApplication.translate("MainWindow", u"Cell Temperature Alarm", None))
        self.lbl_hv_batt_ok.setText(QCoreApplication.translate("MainWindow", u"HV Batt Ok", None))
        self.lbl_can_ok.setText(QCoreApplication.translate("MainWindow", u"CAN Ok", None))
        self.val_speed.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.lbl_kmh.setText(QCoreApplication.translate("MainWindow", u"km/h", None))
        self.val_soc.setText(QCoreApplication.translate("MainWindow", u"000 %", None))
        self.lbl_soc.setText(QCoreApplication.translate("MainWindow", u"SOC", None))
        self.val_inv_volt.setText(QCoreApplication.translate("MainWindow", u"000 V", None))
        self.lbl_inv_volt.setText(QCoreApplication.translate("MainWindow", u"Inverter", None))
        self.lbl_min_cell.setText(QCoreApplication.translate("MainWindow", u"Minimum\n"
"Cell Voltage", None))
        self.val_min_cell.setText(QCoreApplication.translate("MainWindow", u"0.00 V", None))
        self.lbl_max_igbt.setText(QCoreApplication.translate("MainWindow", u"Max\n"
"IGBT Temp", None))
        self.val_max_igbt.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.lbl_max_inv.setText(QCoreApplication.translate("MainWindow", u"Max\n"
"Inverter Temp", None))
        self.val_max_inv.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.lbl_max_motor.setText(QCoreApplication.translate("MainWindow", u"Max\n"
"Motor Temp", None))
        self.val_max_motor.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
    # retranslateUi

