# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QHeaderView,
    QLabel, QMainWindow, QPlainTextEdit, QSizePolicy,
    QStackedWidget, QStatusBar, QTableWidget, QTableWidgetItem,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.actionsettings = QAction(MainWindow)
        self.actionsettings.setObjectName(u"actionsettings")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(30, 10, 771, 441))
        self.page_1 = QWidget()
        self.page_1.setObjectName(u"page_1")
        self.speedbar = QWidget(self.page_1)
        self.speedbar.setObjectName(u"speedbar")
        self.speedbar.setEnabled(True)
        self.speedbar.setGeometry(QRect(310, 30, 81, 371))
        self.speedbar.setMaximumSize(QSize(100, 16777215))
        self.speedbar.setStyleSheet(u"background-color:rgb(255, 41, 3)")
        self.label_4 = QLabel(self.page_1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(670, 410, 91, 31))
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_3 = QLabel(self.page_1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(310, 410, 91, 31))
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.throttlebar = QWidget(self.page_1)
        self.throttlebar.setObjectName(u"throttlebar")
        self.throttlebar.setEnabled(True)
        self.throttlebar.setGeometry(QRect(670, 30, 81, 371))
        self.throttlebar.setMaximumSize(QSize(100, 16777215))
        self.throttlebar.setStyleSheet(u"background-color:rgb(7, 255, 3)")
        self.frontbrakebar = QWidget(self.page_1)
        self.frontbrakebar.setObjectName(u"frontbrakebar")
        self.frontbrakebar.setEnabled(True)
        self.frontbrakebar.setGeometry(QRect(0, 30, 81, 371))
        self.frontbrakebar.setMaximumSize(QSize(100, 16777215))
        self.frontbrakebar.setStyleSheet(u"background-color:rgb(58, 143, 255)")
        self.label = QLabel(self.page_1)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 410, 91, 31))
        self.label.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.label_2 = QLabel(self.page_1)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(110, 410, 91, 31))
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255)")
        self.rearbrakebar = QWidget(self.page_1)
        self.rearbrakebar.setObjectName(u"rearbrakebar")
        self.rearbrakebar.setEnabled(True)
        self.rearbrakebar.setGeometry(QRect(120, 30, 81, 371))
        self.rearbrakebar.setMaximumSize(QSize(100, 16777215))
        self.rearbrakebar.setStyleSheet(u"background-color:rgb(58, 143, 255)")
        self.plainTextEdit = QPlainTextEdit(self.page_1)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(460, 130, 104, 261))
        self.plainTextEdit.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.stackedWidget.addWidget(self.page_1)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.label_7 = QLabel(self.page_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(220, 30, 331, 91))
        font = QFont()
        font.setPointSize(40)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.pack_total_volt = QLabel(self.page_3)
        self.pack_total_volt.setObjectName(u"pack_total_volt")
        self.pack_total_volt.setGeometry(QRect(290, 110, 231, 91))
        self.pack_total_volt.setFont(font)
        self.pack_total_volt.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_9 = QLabel(self.page_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(290, 250, 171, 81))
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.cell_volt = QLabel(self.page_3)
        self.cell_volt.setObjectName(u"cell_volt")
        self.cell_volt.setGeometry(QRect(280, 340, 181, 61))
        self.cell_volt.setFont(font)
        self.cell_volt.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.widget = QWidget(self.page_4)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(386, 10, 16, 421))
        self.widget.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.widget_2 = QWidget(self.page_4)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 211, 741, 16))
        self.widget_2.setStyleSheet(u"background-color:rgb(255, 255, 255)")
        self.label_8 = QLabel(self.page_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(90, 0, 171, 61))
        font1 = QFont()
        font1.setPointSize(25)
        self.label_8.setFont(font1)
        self.label_8.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_10 = QLabel(self.page_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(530, 10, 191, 41))
        self.label_10.setFont(font1)
        self.label_10.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_11 = QLabel(self.page_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(90, 230, 171, 61))
        self.label_11.setFont(font1)
        self.label_11.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_12 = QLabel(self.page_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(410, 240, 361, 51))
        self.label_12.setFont(font1)
        self.label_12.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.running_perc = QLabel(self.page_4)
        self.running_perc.setObjectName(u"running_perc")
        self.running_perc.setGeometry(QRect(90, 100, 171, 51))
        font2 = QFont()
        font2.setPointSize(35)
        self.running_perc.setFont(font2)
        self.running_perc.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.gated_percent = QLabel(self.page_4)
        self.gated_percent.setObjectName(u"gated_percent")
        self.gated_percent.setGeometry(QRect(510, 90, 171, 51))
        self.gated_percent.setFont(font2)
        self.gated_percent.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.running_temp = QLabel(self.page_4)
        self.running_temp.setObjectName(u"running_temp")
        self.running_temp.setGeometry(QRect(90, 330, 171, 51))
        self.running_temp.setFont(font2)
        self.running_temp.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.cur_max_temp = QLabel(self.page_4)
        self.cur_max_temp.setObjectName(u"cur_max_temp")
        self.cur_max_temp.setGeometry(QRect(500, 330, 171, 51))
        self.cur_max_temp.setFont(font2)
        self.cur_max_temp.setStyleSheet(u"color:rgb(255, 255, 255);")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.front_rear_temp_table = QTableWidget(self.page_5)
        if (self.front_rear_temp_table.columnCount() < 5):
            self.front_rear_temp_table.setColumnCount(5)
        if (self.front_rear_temp_table.rowCount() < 4):
            self.front_rear_temp_table.setRowCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 1, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 2, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 3, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(0, 4, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 3, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(1, 4, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 1, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 2, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 3, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(2, 4, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 0, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 1, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 2, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 3, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.front_rear_temp_table.setItem(3, 4, __qtablewidgetitem18)
        self.front_rear_temp_table.setObjectName(u"front_rear_temp_table")
        self.front_rear_temp_table.setGeometry(QRect(110, 10, 511, 221))
        font3 = QFont()
        font3.setPointSize(15)
        self.front_rear_temp_table.setFont(font3)
        self.front_rear_temp_table.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.front_rear_temp_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.front_rear_temp_table.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.front_rear_temp_table.setWordWrap(True)
        self.front_rear_temp_table.setRowCount(4)
        self.front_rear_temp_table.setColumnCount(5)
        self.front_rear_temp_table.horizontalHeader().setVisible(False)
        self.front_rear_temp_table.horizontalHeader().setCascadingSectionResizes(True)
        self.front_rear_temp_table.horizontalHeader().setDefaultSectionSize(100)
        self.front_rear_temp_table.horizontalHeader().setHighlightSections(True)
        self.front_rear_temp_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.front_rear_temp_table.horizontalHeader().setStretchLastSection(True)
        self.front_rear_temp_table.verticalHeader().setVisible(False)
        self.front_rear_temp_table.verticalHeader().setDefaultSectionSize(50)
        self.front_rear_temp_table.verticalHeader().setHighlightSections(True)
        self.front_rear_temp_table.verticalHeader().setProperty(u"showSortIndicator", False)
        self.front_rear_temp_table.verticalHeader().setStretchLastSection(True)
        self.motor_loop_temp_table = QTableWidget(self.page_5)
        if (self.motor_loop_temp_table.columnCount() < 3):
            self.motor_loop_temp_table.setColumnCount(3)
        if (self.motor_loop_temp_table.rowCount() < 2):
            self.motor_loop_temp_table.setRowCount(2)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(0, 0, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(0, 1, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(0, 2, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(1, 0, __qtablewidgetitem22)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(1, 1, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.motor_loop_temp_table.setItem(1, 2, __qtablewidgetitem24)
        self.motor_loop_temp_table.setObjectName(u"motor_loop_temp_table")
        self.motor_loop_temp_table.setGeometry(QRect(0, 280, 321, 131))
        self.motor_loop_temp_table.setFont(font3)
        self.motor_loop_temp_table.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.motor_loop_temp_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.motor_loop_temp_table.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.motor_loop_temp_table.setWordWrap(True)
        self.motor_loop_temp_table.setRowCount(2)
        self.motor_loop_temp_table.setColumnCount(3)
        self.motor_loop_temp_table.horizontalHeader().setVisible(False)
        self.motor_loop_temp_table.horizontalHeader().setCascadingSectionResizes(True)
        self.motor_loop_temp_table.horizontalHeader().setDefaultSectionSize(100)
        self.motor_loop_temp_table.horizontalHeader().setHighlightSections(True)
        self.motor_loop_temp_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.motor_loop_temp_table.horizontalHeader().setStretchLastSection(True)
        self.motor_loop_temp_table.verticalHeader().setVisible(False)
        self.motor_loop_temp_table.verticalHeader().setDefaultSectionSize(50)
        self.motor_loop_temp_table.verticalHeader().setHighlightSections(True)
        self.motor_loop_temp_table.verticalHeader().setProperty(u"showSortIndicator", False)
        self.motor_loop_temp_table.verticalHeader().setStretchLastSection(True)
        self.inv_loop_temp_table = QTableWidget(self.page_5)
        if (self.inv_loop_temp_table.columnCount() < 3):
            self.inv_loop_temp_table.setColumnCount(3)
        if (self.inv_loop_temp_table.rowCount() < 2):
            self.inv_loop_temp_table.setRowCount(2)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(0, 0, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(0, 1, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(0, 2, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(1, 0, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(1, 1, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.inv_loop_temp_table.setItem(1, 2, __qtablewidgetitem30)
        self.inv_loop_temp_table.setObjectName(u"inv_loop_temp_table")
        self.inv_loop_temp_table.setGeometry(QRect(400, 280, 321, 131))
        self.inv_loop_temp_table.setFont(font3)
        self.inv_loop_temp_table.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.inv_loop_temp_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.inv_loop_temp_table.setHorizontalScrollMode(QAbstractItemView.ScrollMode.ScrollPerItem)
        self.inv_loop_temp_table.setWordWrap(True)
        self.inv_loop_temp_table.setRowCount(2)
        self.inv_loop_temp_table.setColumnCount(3)
        self.inv_loop_temp_table.horizontalHeader().setVisible(False)
        self.inv_loop_temp_table.horizontalHeader().setCascadingSectionResizes(True)
        self.inv_loop_temp_table.horizontalHeader().setDefaultSectionSize(100)
        self.inv_loop_temp_table.horizontalHeader().setHighlightSections(True)
        self.inv_loop_temp_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.inv_loop_temp_table.horizontalHeader().setStretchLastSection(True)
        self.inv_loop_temp_table.verticalHeader().setVisible(False)
        self.inv_loop_temp_table.verticalHeader().setDefaultSectionSize(50)
        self.inv_loop_temp_table.verticalHeader().setHighlightSections(True)
        self.inv_loop_temp_table.verticalHeader().setProperty(u"showSortIndicator", False)
        self.inv_loop_temp_table.verticalHeader().setStretchLastSection(True)
        self.stackedWidget.addWidget(self.page_5)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.CVT_table = QTableWidget(self.page_2)
        if (self.CVT_table.columnCount() < 2):
            self.CVT_table.setColumnCount(2)
        if (self.CVT_table.rowCount() < 6):
            self.CVT_table.setRowCount(6)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.CVT_table.setItem(0, 0, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.CVT_table.setItem(0, 1, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.CVT_table.setItem(1, 0, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.CVT_table.setItem(1, 1, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.CVT_table.setItem(2, 0, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.CVT_table.setItem(2, 1, __qtablewidgetitem36)
        font4 = QFont()
        font4.setPointSize(19)
        __qtablewidgetitem37 = QTableWidgetItem()
        __qtablewidgetitem37.setFont(font4);
        self.CVT_table.setItem(3, 0, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.CVT_table.setItem(3, 1, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.CVT_table.setItem(4, 0, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.CVT_table.setItem(4, 1, __qtablewidgetitem40)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.CVT_table.setItem(5, 0, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.CVT_table.setItem(5, 1, __qtablewidgetitem42)
        self.CVT_table.setObjectName(u"CVT_table")
        self.CVT_table.setEnabled(True)
        self.CVT_table.setGeometry(QRect(200, 100, 401, 321))
        self.CVT_table.setFont(font4)
        self.CVT_table.setStyleSheet(u"\n"
"color: rgb(255, 255, 255);\n"
"")
        self.CVT_table.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.CVT_table.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.CVT_table.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.CVT_table.setRowCount(6)
        self.CVT_table.setColumnCount(2)
        self.CVT_table.horizontalHeader().setVisible(False)
        self.CVT_table.horizontalHeader().setCascadingSectionResizes(True)
        self.CVT_table.horizontalHeader().setDefaultSectionSize(250)
        self.CVT_table.horizontalHeader().setHighlightSections(True)
        self.CVT_table.horizontalHeader().setProperty(u"showSortIndicator", False)
        self.CVT_table.horizontalHeader().setStretchLastSection(True)
        self.CVT_table.verticalHeader().setVisible(False)
        self.CVT_table.verticalHeader().setDefaultSectionSize(50)
        self.CVT_table.verticalHeader().setStretchLastSection(False)
        self.charging_status_light = QWidget(self.page_2)
        self.charging_status_light.setObjectName(u"charging_status_light")
        self.charging_status_light.setGeometry(QRect(230, 0, 41, 41))
        self.charging_status_light.setStyleSheet(u"background-color: rgb(255, 14, 30);\n"
"border-radius: 20px\n"
"")
        self.balancing_status_light = QWidget(self.page_2)
        self.balancing_status_light.setObjectName(u"balancing_status_light")
        self.balancing_status_light.setGeometry(QRect(230, 50, 41, 41))
        self.balancing_status_light.setStyleSheet(u"background-color: rgb(255, 14, 30);\n"
"border-radius: 20px\n"
"")
        self.label_5 = QLabel(self.page_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(280, 0, 221, 41))
        font5 = QFont()
        font5.setPointSize(17)
        self.label_5.setFont(font5)
        self.label_5.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.label_6 = QLabel(self.page_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(280, 50, 221, 41))
        self.label_6.setFont(font5)
        self.label_6.setStyleSheet(u"color:rgb(255, 255, 255)")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionsettings.setText(QCoreApplication.translate("MainWindow", u"settings", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Throttle", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Front Brake", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Rear Brake", None))
        self.plainTextEdit.setPlainText(QCoreApplication.translate("MainWindow", u"Stats for the car:\n"
"\n"
"\n"
".\n"
".\n"
".\n"
".\n"
".\n"
"", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Pack Total", None))
        self.pack_total_volt.setText(QCoreApplication.translate("MainWindow", u"000V", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Cell", None))
        self.cell_volt.setText(QCoreApplication.translate("MainWindow", u"000V", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Running", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Gated", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Running", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Current Max Temp.", None))
        self.running_perc.setText(QCoreApplication.translate("MainWindow", u"00.0%", None))
        self.gated_percent.setText(QCoreApplication.translate("MainWindow", u"00.0%", None))
        self.running_temp.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))
        self.cur_max_temp.setText(QCoreApplication.translate("MainWindow", u"00.0 C", None))

        __sortingEnabled = self.front_rear_temp_table.isSortingEnabled()
        self.front_rear_temp_table.setSortingEnabled(False)
        ___qtablewidgetitem = self.front_rear_temp_table.item(0, 1)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"FL", None));
        ___qtablewidgetitem1 = self.front_rear_temp_table.item(0, 2)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"FR", None));
        ___qtablewidgetitem2 = self.front_rear_temp_table.item(0, 3)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"RL", None));
        ___qtablewidgetitem3 = self.front_rear_temp_table.item(0, 4)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"RR", None));
        ___qtablewidgetitem4 = self.front_rear_temp_table.item(1, 0)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Motor", None));
        ___qtablewidgetitem5 = self.front_rear_temp_table.item(1, 1)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem6 = self.front_rear_temp_table.item(1, 2)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem7 = self.front_rear_temp_table.item(1, 3)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem8 = self.front_rear_temp_table.item(1, 4)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem9 = self.front_rear_temp_table.item(2, 0)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("MainWindow", u"IGBT", None));
        ___qtablewidgetitem10 = self.front_rear_temp_table.item(2, 1)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem11 = self.front_rear_temp_table.item(2, 2)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem12 = self.front_rear_temp_table.item(2, 3)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem13 = self.front_rear_temp_table.item(2, 4)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem14 = self.front_rear_temp_table.item(3, 0)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("MainWindow", u"Cold Plate", None));
        ___qtablewidgetitem15 = self.front_rear_temp_table.item(3, 1)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem16 = self.front_rear_temp_table.item(3, 2)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem17 = self.front_rear_temp_table.item(3, 3)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem18 = self.front_rear_temp_table.item(3, 4)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        self.front_rear_temp_table.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.motor_loop_temp_table.isSortingEnabled()
        self.motor_loop_temp_table.setSortingEnabled(False)
        ___qtablewidgetitem19 = self.motor_loop_temp_table.item(0, 1)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("MainWindow", u"Start", None));
        ___qtablewidgetitem20 = self.motor_loop_temp_table.item(0, 2)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("MainWindow", u"End", None));
        ___qtablewidgetitem21 = self.motor_loop_temp_table.item(1, 0)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("MainWindow", u"Motor Loop", None));
        ___qtablewidgetitem22 = self.motor_loop_temp_table.item(1, 1)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem23 = self.motor_loop_temp_table.item(1, 2)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        self.motor_loop_temp_table.setSortingEnabled(__sortingEnabled1)


        __sortingEnabled2 = self.inv_loop_temp_table.isSortingEnabled()
        self.inv_loop_temp_table.setSortingEnabled(False)
        ___qtablewidgetitem24 = self.inv_loop_temp_table.item(0, 1)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("MainWindow", u"Start", None));
        ___qtablewidgetitem25 = self.inv_loop_temp_table.item(0, 2)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("MainWindow", u"End", None));
        ___qtablewidgetitem26 = self.inv_loop_temp_table.item(1, 0)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("MainWindow", u"Inverter Loop", None));
        ___qtablewidgetitem27 = self.inv_loop_temp_table.item(1, 1)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem28 = self.inv_loop_temp_table.item(1, 2)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        self.inv_loop_temp_table.setSortingEnabled(__sortingEnabled2)


        __sortingEnabled3 = self.CVT_table.isSortingEnabled()
        self.CVT_table.setSortingEnabled(False)
        ___qtablewidgetitem29 = self.CVT_table.item(0, 0)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("MainWindow", u"Current", None));
        ___qtablewidgetitem30 = self.CVT_table.item(0, 1)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("MainWindow", u"0A", None));
        ___qtablewidgetitem31 = self.CVT_table.item(1, 0)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("MainWindow", u"Voltage", None));
        ___qtablewidgetitem32 = self.CVT_table.item(1, 1)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("MainWindow", u"0V", None));
        ___qtablewidgetitem33 = self.CVT_table.item(2, 0)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("MainWindow", u"Min Cell Temp.", None));
        ___qtablewidgetitem34 = self.CVT_table.item(2, 1)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("MainWindow", u"0 C", None));
        ___qtablewidgetitem35 = self.CVT_table.item(3, 0)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("MainWindow", u"Max Cell Temp.", None));
        ___qtablewidgetitem36 = self.CVT_table.item(3, 1)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("MainWindow", u"0V", None));
        ___qtablewidgetitem37 = self.CVT_table.item(4, 0)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("MainWindow", u"Min Cell Volt.", None));
        ___qtablewidgetitem38 = self.CVT_table.item(4, 1)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("MainWindow", u"0V", None));
        ___qtablewidgetitem39 = self.CVT_table.item(5, 0)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("MainWindow", u"Max Cell Volt.", None));
        ___qtablewidgetitem40 = self.CVT_table.item(5, 1)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("MainWindow", u"0V", None));
        self.CVT_table.setSortingEnabled(__sortingEnabled3)

        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Charging Status", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Balancing Status", None))
    # retranslateUi

